#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Tapat.Resource", IsApplication=true)]

namespace Tapat
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::BranchXamarinSDK.Droid.Resource.String.library_name = global::Tapat.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int fingerprint = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int fp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int logob = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int logow = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int rpcoat = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050048
			public const int Maghintay = 2131034184;
			
			// aapt resource value: 0x7f050047
			public const int PleaseWait = 2131034183;
			
			// aapt resource value: 0x7f050004
			public const int President = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int VP = 2131034119;
			
			// aapt resource value: 0x7f05005e
			public const int b_date = 2131034206;
			
			// aapt resource value: 0x7f05007c
			public const int barangg = 2131034236;
			
			// aapt resource value: 0x7f05007d
			public const int baranggay = 2131034237;
			
			// aapt resource value: 0x7f05005f
			public const int bdate = 2131034207;
			
			// aapt resource value: 0x7f050070
			public const int biodata = 2131034224;
			
			// aapt resource value: 0x7f05006e
			public const int biometdata = 2131034222;
			
			// aapt resource value: 0x7f05006f
			public const int biometrics_data = 2131034223;
			
			// aapt resource value: 0x7f05005d
			public const int birthdatee = 2131034205;
			
			// aapt resource value: 0x7f05000d
			public const int blank = 2131034125;
			
			// aapt resource value: 0x7f05007e
			public const int brgy = 2131034238;
			
			// aapt resource value: 0x7f05002d
			public const int button = 2131034157;
			
			// aapt resource value: 0x7f05004a
			public const int buttons = 2131034186;
			
			// aapt resource value: 0x7f050035
			public const int capture_button = 2131034165;
			
			// aapt resource value: 0x7f050002
			public const int choose = 2131034114;
			
			// aapt resource value: 0x7f05007b
			public const int city = 2131034235;
			
			// aapt resource value: 0x7f050079
			public const int cityy = 2131034233;
			
			// aapt resource value: 0x7f050063
			public const int civil = 2131034211;
			
			// aapt resource value: 0x7f050064
			public const int civil_status = 2131034212;
			
			// aapt resource value: 0x7f050043
			public const int close_poll = 2131034179;
			
			// aapt resource value: 0x7f05004e
			public const int confirm_VVPAT = 2131034190;
			
			// aapt resource value: 0x7f05002f
			public const int confirm_button = 2131034159;
			
			// aapt resource value: 0x7f050065
			public const int cstatus = 2131034213;
			
			// aapt resource value: 0x7f05007a
			public const int cty = 2131034234;
			
			// aapt resource value: 0x7f050066
			public const int details = 2131034214;
			
			// aapt resource value: 0x7f050055
			public const int first_name = 2131034197;
			
			// aapt resource value: 0x7f050054
			public const int firstname = 2131034196;
			
			// aapt resource value: 0x7f050056
			public const int fname = 2131034198;
			
			// aapt resource value: 0x7f050031
			public const int fptext_eng = 2131034161;
			
			// aapt resource value: 0x7f050036
			public const int fptext_tag = 2131034166;
			
			// aapt resource value: 0x7f050060
			public const int gender = 2131034208;
			
			// aapt resource value: 0x7f05001d
			public const int houserep = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int houserep1 = 2131034142;
			
			// aapt resource value: 0x7f05001c
			public const int houserepre = 2131034140;
			
			// aapt resource value: 0x7f050082
			public const int id1 = 2131034242;
			
			// aapt resource value: 0x7f050083
			public const int id2 = 2131034243;
			
			// aapt resource value: 0x7f050084
			public const int id3 = 2131034244;
			
			// aapt resource value: 0x7f050085
			public const int id4 = 2131034245;
			
			// aapt resource value: 0x7f050086
			public const int id5 = 2131034246;
			
			// aapt resource value: 0x7f050087
			public const int id6 = 2131034247;
			
			// aapt resource value: 0x7f050088
			public const int id7 = 2131034248;
			
			// aapt resource value: 0x7f050089
			public const int id8 = 2131034249;
			
			// aapt resource value: 0x7f05008a
			public const int id9 = 2131034250;
			
			// aapt resource value: 0x7f050074
			public const int id_num = 2131034228;
			
			// aapt resource value: 0x7f05003a
			public const int img_fp = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int img_rop_coa = 2131034171;
			
			// aapt resource value: 0x7f050001
			public const int img_tapat = 2131034113;
			
			// aapt resource value: 0x7f050052
			public const int info = 2131034194;
			
			// aapt resource value: 0x7f050058
			public const int last_name = 2131034200;
			
			// aapt resource value: 0x7f050057
			public const int lastname = 2131034199;
			
			// aapt resource value: 0x7f050059
			public const int lname = 2131034201;
			
			// aapt resource value: 0x7f050041
			public const int login = 2131034177;
			
			// aapt resource value: 0x7f050040
			public const int login_button = 2131034176;
			
			// aapt resource value: 0x7f050046
			public const int logout_butt = 2131034182;
			
			// aapt resource value: 0x7f050026
			public const int lungsod = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int lungsod1 = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int lungsod2 = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int lungsod3 = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int lungsod4 = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int lungsod5 = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int lungsod6 = 2131034156;
			
			// aapt resource value: 0x7f050039
			public const int main = 2131034169;
			
			// aapt resource value: 0x7f050038
			public const int mainmenu = 2131034168;
			
			// aapt resource value: 0x7f050044
			public const int man_count = 2131034180;
			
			// aapt resource value: 0x7f050020
			public const int mayor = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int mayor1 = 2131034145;
			
			// aapt resource value: 0x7f05001f
			public const int mayorr = 2131034143;
			
			// aapt resource value: 0x7f05005b
			public const int middle_name = 2131034203;
			
			// aapt resource value: 0x7f05005a
			public const int middlename = 2131034202;
			
			// aapt resource value: 0x7f05005c
			public const int midname = 2131034204;
			
			// aapt resource value: 0x7f050042
			public const int open_poll = 2131034178;
			
			// aapt resource value: 0x7f050025
			public const int panglungsod = 2131034149;
			
			// aapt resource value: 0x7f05001a
			public const int party = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int party1 = 2131034139;
			
			// aapt resource value: 0x7f050019
			public const int partylist = 2131034137;
			
			// aapt resource value: 0x7f05003f
			public const int password = 2131034175;
			
			// aapt resource value: 0x7f050051
			public const int picture = 2131034193;
			
			// aapt resource value: 0x7f050005
			public const int pres = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int pres1 = 2131034118;
			
			// aapt resource value: 0x7f05004b
			public const int print_ballot = 2131034187;
			
			// aapt resource value: 0x7f050081
			public const int proceed_butt = 2131034241;
			
			// aapt resource value: 0x7f050076
			public const int prov = 2131034230;
			
			// aapt resource value: 0x7f050078
			public const int province = 2131034232;
			
			// aapt resource value: 0x7f050077
			public const int provincee = 2131034231;
			
			// aapt resource value: 0x7f05002e
			public const int recapture_button = 2131034158;
			
			// aapt resource value: 0x7f050067
			public const int reg = 2131034215;
			
			// aapt resource value: 0x7f050069
			public const int reg_date = 2131034217;
			
			// aapt resource value: 0x7f050072
			public const int reg_record = 2131034226;
			
			// aapt resource value: 0x7f05006c
			public const int reg_status = 2131034220;
			
			// aapt resource value: 0x7f05006a
			public const int regdate = 2131034218;
			
			// aapt resource value: 0x7f050068
			public const int regisdate = 2131034216;
			
			// aapt resource value: 0x7f050071
			public const int regisrecord = 2131034225;
			
			// aapt resource value: 0x7f05006b
			public const int registatus = 2131034219;
			
			// aapt resource value: 0x7f05006d
			public const int regstatus = 2131034221;
			
			// aapt resource value: 0x7f050030
			public const int relativeLayout1 = 2131034160;
			
			// aapt resource value: 0x7f050000
			public const int relative_main = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int scrollView1 = 2131034115;
			
			// aapt resource value: 0x7f05000c
			public const int sen1 = 2131034124;
			
			// aapt resource value: 0x7f050016
			public const int sen10 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int sen11 = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int sen12 = 2131034136;
			
			// aapt resource value: 0x7f05000e
			public const int sen2 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int sen3 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int sen4 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int sen5 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int sen6 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int sen7 = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int sen8 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int sen9 = 2131034133;
			
			// aapt resource value: 0x7f05000b
			public const int senator = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int senators = 2131034122;
			
			// aapt resource value: 0x7f05004f
			public const int send = 2131034191;
			
			// aapt resource value: 0x7f050061
			public const int sex = 2131034209;
			
			// aapt resource value: 0x7f050062
			public const int sexx = 2131034210;
			
			// aapt resource value: 0x7f050049
			public const int tagalog = 2131034185;
			
			// aapt resource value: 0x7f050045
			public const int tally = 2131034181;
			
			// aapt resource value: 0x7f050033
			public const int textView1 = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int textView2 = 2131034164;
			
			// aapt resource value: 0x7f050032
			public const int textView3 = 2131034162;
			
			// aapt resource value: 0x7f05004c
			public const int textView4 = 2131034188;
			
			// aapt resource value: 0x7f05004d
			public const int textView8 = 2131034189;
			
			// aapt resource value: 0x7f05003e
			public const int text_pass = 2131034174;
			
			// aapt resource value: 0x7f05003c
			public const int text_user = 2131034172;
			
			// aapt resource value: 0x7f050050
			public const int try_again = 2131034192;
			
			// aapt resource value: 0x7f05003d
			public const int user_id = 2131034173;
			
			// aapt resource value: 0x7f050037
			public const int v_login = 2131034167;
			
			// aapt resource value: 0x7f05007f
			public const int vcenter = 2131034239;
			
			// aapt resource value: 0x7f050023
			public const int vice = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int vice1 = 2131034148;
			
			// aapt resource value: 0x7f050022
			public const int vicemayor = 2131034146;
			
			// aapt resource value: 0x7f050073
			public const int vidnum = 2131034227;
			
			// aapt resource value: 0x7f050053
			public const int voter_info = 2131034195;
			
			// aapt resource value: 0x7f050075
			public const int voteridnum = 2131034229;
			
			// aapt resource value: 0x7f050080
			public const int voting_center = 2131034240;
			
			// aapt resource value: 0x7f050009
			public const int vp1 = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int vpres = 2131034120;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Ballot_Votes = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Capture_Ballot = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Cast_Vote = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Close_Poll = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int EXAMPLE = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Fingerprint_BEI = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Fingerprint_Voter = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Login = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Logout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int MainMenu = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int PleaseWait = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Sample_Profile = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Scrolling = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Sent_To_Cencas = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Tally_Votes = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int User_Votes = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Verify_VVPAT = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Voter_Profile = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int VVPAT_IDEntries = 2130903058;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
